services:
  php:
    build: .
    container_name: esportify-php
    dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0.41
    container_name: esportify-db
    restart: always
    environment:
      MYSQL_DATABASE: esportify_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: esport
      MYSQL_PASSWORD: esport123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
